name: groovr
description: groovr, the music school.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  sliding_up_panel: ^1.0.2
  audioplayers: ^0.15.1
  expandable: ^4.1.3
  photo_view: ^0.9.2
  flare_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
    - icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
          # weight: 900

    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
